#!/usr/bin/env bash
# QEMU launch defaults for the ARM64 Raspberry Pi 3 platform.

QEMU_MACHINE_DEFAULT="raspi3b"
QEMU_CPU_DEFAULT="cortex-a53"
QEMU_MEMORY_DEFAULT="1G"
QEMU_SMP_DEFAULT="4"
QEMU_BLOCK_ENABLED_DEFAULT="1"
QEMU_BLOCK_IF_DEFAULT="sd"
QEMU_KERNEL_IMAGE_DEFAULT="$ROOT_DIR/build/images/kernel-arm64-raspi3.bin"
QEMU_DISK_IMAGE_DEFAULT="$ROOT_DIR/build/images/disk-arm64-raspi3.img"
QEMU_KERNEL_LOADER_ADDR_DEFAULT="0x02010000"
QEMU_BLOCK_DEVICE_DEFAULT=""
QEMU_GPU_DEVICE_DEFAULT=""
QEMU_INPUT_DEVICE_DEFAULT=""
QEMU_NET_DEVICE_MODEL_DEFAULT=""
