# Raspberry Pi 3 B+ AArch64 Wi-Fi bring-up profile.
#
# This profile intentionally leaves the stable raspi3-arm64.conf unchanged
# while the SDHOST/SDIO/CYW43455 path is validated on real hardware.
# Install the separately licensed firmware before building a complete disk:
#   tools/fetch_raspi3_wifi_firmware.sh --accept-license

TARGET_ARCH=arm64
TARGET_PLATFORM=raspi3
SMP_CPUS=4
ENABLE_NET=yes
ENABLE_WIFI=yes
ENABLE_GPU=no
ENABLE_HDMI=yes
ENABLE_ILI9341=no
ENABLE_USB=yes
HDMI_WIDTH=1280
HDMI_HEIGHT=720
