# Raspberry Pi 3 B+ AArch32 Wi-Fi bring-up profile.
#
# It exercises the same common SDHOST/SDIO drivers as the AArch64 profile.
# Raspberry Pi 2 remains unchanged because it has no on-board Wi-Fi module.
# Install the separately licensed firmware before building a complete disk:
#   tools/fetch_raspi3_wifi_firmware.sh --accept-license

TARGET_ARCH=arm32
TARGET_PLATFORM=raspi3
SMP_CPUS=4
ENABLE_NET=yes
ENABLE_WIFI=yes
ENABLE_GPU=no
ENABLE_HDMI=yes
ENABLE_ILI9341=no
ENABLE_USB=yes
HDMI_WIDTH=1280
HDMI_HEIGHT=720
