# Raspberry Pi 3 B+ hardware reference.
TARGET_ARCH=arm64
TARGET_PLATFORM=raspi3
SMP_CPUS=4
ENABLE_NET=no
ENABLE_GPU=no
ENABLE_HDMI=yes
ENABLE_ILI9341=no
ENABLE_USB=yes
BUILD_NEWLIB=no
BUILD_TCC=no
BUILD_BSD=no
BUILD_NCURSES=no
BUILD_NANO=no
DEVICE_TREE=bcm2710-rpi-3-b-plus.dtb
DTOVERLAY=disable-bt
