# Raspberry Pi 2 Model B v1.1 / QEMU raspi2 target.
TARGET_ARCH=arm32
TARGET_PLATFORM=raspi2
SMP_CPUS=4
ENABLE_NET=no
ENABLE_GPU=no
BUILD_NEWLIB=no
BUILD_TCC=no
BUILD_BSD=no
BUILD_NCURSES=no
BUILD_NANO=no
