#ifndef ARMOS_BSDINSTALL_NBTOOL_CONFIG_H
#define ARMOS_BSDINSTALL_NBTOOL_CONFIG_H

#ifndef HAVE_NBTOOL_CONFIG_H
#define HAVE_NBTOOL_CONFIG_H 1
#endif

#define HAVE_FUTIMES 0
#define HAVE_STRUCT_STAT_ST_FLAGS 0

#endif /* ARMOS_BSDINSTALL_NBTOOL_CONFIG_H */
