/*
 * ArmOS
 * Copyright (c) 2026 Mohamed Ennassiri
 *
 * Licensed under the Apache License, Version 2.0.
 * See LICENSE for details.
 *
 * File: arch/arm32/include/asm/platform/pi3.h
 * Layer: ARM32 / Raspberry Pi 3 hardware platform map
 *
 * Responsibilities:
 * - Describe the Raspberry Pi 3 AArch32 hardware target.
 * - Keep real-board policy out of the QEMU raspi2 profile.
 *
 * Notes:
 * - BCM2837 keeps the BCM2836-style peripheral layout used by our current
 *   Raspberry Pi drivers. The RASPI2_* names below are compatibility aliases
 *   for those shared drivers, not an assertion that the board is a Pi 2.
 */

#ifndef _ASM_ARM32_PLATFORM_PI3_H
#define _ASM_ARM32_PLATFORM_PI3_H

#include <kernel/types.h>

#define RASPI2_RAM_START             0x00000000u
#define RASPI2_KERNEL_LINK_ADDR      0x02010000u

#define RASPI2_PERIPHERAL_BASE       0x3F000000u
#define RASPI2_PERIPHERAL_END        0x40000000u
#define RASPI2_IRQCTRL_BASE          0x3F00B000u
#define RASPI2_IRQCTRL_SECTION_BASE  0x3F000000u
#define RASPI2_LOCAL_IRQ_BASE        0x40000000u
#define RASPI2_LOCAL_IRQ_END         0x40100000u
#define RASPI2_UART0_BASE            0x3F201000u
#define RASPI2_UART0_SECTION_BASE    0x3F200000u
#define RASPI2_EMMC_BASE             0x3F300000u
#define RASPI2_EMMC_SECTION_BASE     0x3F300000u

#define RASPI2_KERNEL_MMIO_IRQ_BASE  0xF0000000u
#define RASPI2_KERNEL_MMIO_UART_BASE 0xF0100000u
#define RASPI2_KERNEL_MMIO_EMMC_BASE 0xF0200000u
#define RASPI2_KERNEL_MMIO_IRQCTRL2_BASE 0xF0300000u
#define RASPI2_KERNEL_MMIO_SECTION   0x00100000u

#define ARMOS_PLATFORM_NAME                      "Raspberry Pi 3"
#define ARMOS_PLATFORM_CPU_MODEL                 "ARM Cortex-A53 @ Raspberry Pi 3 (AArch32)"
#define ARMOS_PLATFORM_CPU_FEATURES              "swp half thumb fastmult vfp edsp neon vfpv4 tls"
#define ARMOS_PLATFORM_HARDWARE_NAME             "ArmOS Raspberry Pi 3"
#define ARMOS_PLATFORM_RAM_START                 RASPI2_RAM_START
#define ARMOS_PLATFORM_RAM_FALLBACK_SIZE         (RASPI2_PERIPHERAL_BASE - RASPI2_RAM_START)
#define ARMOS_PLATFORM_RAM_PROBE_MAX_MB          1008u
#define ARMOS_PLATFORM_DEFAULT_CPU_COUNT         4u
#define ARMOS_PLATFORM_TIMER_FALLBACK_HZ         1000000u
#define ARMOS_PLATFORM_TIMER_CNTFRQ_QUIRK_HZ     19200000u
#define ARMOS_PLATFORM_TIMER_CNTFRQ_QUIRK_EFFECTIVE_HZ 1000000u
#define ARMOS_PLATFORM_DEVICE_START              RASPI2_PERIPHERAL_BASE
#define ARMOS_PLATFORM_DEVICE_END                RASPI2_PERIPHERAL_END

#define ARMOS_PLATFORM_UART0_PHYS_BASE           RASPI2_UART0_BASE
#define ARMOS_PLATFORM_UART0_PHYS_SECTION_BASE   RASPI2_UART0_SECTION_BASE
#define ARMOS_PLATFORM_UART0_KERNEL_BASE \
    (RASPI2_KERNEL_MMIO_UART_BASE + (RASPI2_UART0_BASE - RASPI2_UART0_SECTION_BASE))
#define ARMOS_PLATFORM_UART0_CLOCK_HZ            4000000u
#define ARMOS_PLATFORM_UART0_BAUD                115200u

#define ARMOS_PLATFORM_UART_IRQ                  57u
#define ARMOS_PLATFORM_TIMER_IRQ                 1u
#define ARMOS_PLATFORM_SGI_TLB_SHOOTDOWN_IRQ     0u

#define ARMOS_PLATFORM_KERNEL_MMIO_SECTION_SIZE  RASPI2_KERNEL_MMIO_SECTION
#define ARMOS_PLATFORM_KERNEL_MMIO_IRQCTRL_BASE  RASPI2_KERNEL_MMIO_IRQ_BASE
#define ARMOS_PLATFORM_KERNEL_MMIO_UART_BASE     RASPI2_KERNEL_MMIO_UART_BASE
#define ARMOS_PLATFORM_KERNEL_MMIO_EMMC_BASE     RASPI2_KERNEL_MMIO_EMMC_BASE
#define ARMOS_PLATFORM_KERNEL_MMIO_IRQCTRL2_BASE \
    RASPI2_KERNEL_MMIO_IRQCTRL2_BASE
#define ARMOS_PLATFORM_IRQCTRL2_PHYS_SECTION_BASE \
    RASPI2_IRQCTRL_SECTION_BASE

#define ARMOS_PLATFORM_HAS_EMMC                  1u
#define ARMOS_PLATFORM_EMMC_PHYS_BASE            RASPI2_EMMC_BASE
#define ARMOS_PLATFORM_EMMC_PHYS_SECTION_BASE    RASPI2_EMMC_SECTION_BASE
#define ARMOS_PLATFORM_EMMC_KERNEL_BASE \
    (RASPI2_KERNEL_MMIO_EMMC_BASE + (RASPI2_EMMC_BASE - RASPI2_EMMC_SECTION_BASE))

#define ARMOS_PLATFORM_IRQCTRL_PHYS_START        RASPI2_LOCAL_IRQ_BASE
#define ARMOS_PLATFORM_IRQCTRL_PHYS_END          RASPI2_LOCAL_IRQ_END
#define ARMOS_PLATFORM_IRQ_TARGETS_AUTO_MANAGED  0
#define ARMOS_PLATFORM_HAS_PSCI                  0
#define ARMOS_PLATFORM_HAS_SMP_IPI               1u

#endif /* _ASM_ARM32_PLATFORM_PI3_H */
