/*
 * ArmOS
 * Copyright (c) 2026 Mohamed Ennassiri
 *
 * Licensed under the Apache License, Version 2.0.
 * See LICENSE for details.
 *
 * File: arch/arm32/include/asm/platform/raspi3.h
 * Layer: ARM32 / Raspberry Pi 3 hardware platform map
 *
 * Responsibilities:
 * - Describe the Raspberry Pi 3 AArch32 hardware target.
 * - Keep real-board policy out of the QEMU raspi2 profile.
 *
 * Notes:
 * - BCM2837 keeps the BCM2836-style peripheral layout used by the shared
 *   Raspberry Pi platform drivers.
 */

#ifndef _ASM_ARM32_PLATFORM_RASPI3_H
#define _ASM_ARM32_PLATFORM_RASPI3_H

#include <kernel/types.h>

#define RASPI3_RAM_START             0x00000000u
#define RASPI3_KERNEL_LINK_ADDR      0x02010000u

#define RASPI3_PERIPHERAL_BASE       0x3F000000u
#define RASPI3_PERIPHERAL_END        0x40000000u
#define RASPI3_IRQCTRL_BASE          0x3F00B000u
#define RASPI3_IRQCTRL_SECTION_BASE  0x3F000000u
#define RASPI3_LOCAL_IRQ_BASE        0x40000000u
#define RASPI3_LOCAL_IRQ_END         0x40100000u
#define RASPI3_UART0_BASE            0x3F201000u
#define RASPI3_UART0_SECTION_BASE    0x3F200000u
#define RASPI3_GPIO_BASE             0x3F200000u
#define RASPI3_SDHOST_BASE           0x3F202000u
#define RASPI3_EMMC_BASE             0x3F300000u
#define RASPI3_EMMC_SECTION_BASE     0x3F300000u
#define RASPI3_USB_BASE              0x3F980000u
#define RASPI3_USB_SECTION_BASE      0x3F900000u

#define RASPI3_KERNEL_MMIO_IRQ_BASE  0xF0000000u
#define RASPI3_KERNEL_MMIO_UART_BASE 0xF0100000u
#define RASPI3_KERNEL_MMIO_EMMC_BASE 0xF0200000u
#define RASPI3_KERNEL_MMIO_IRQCTRL2_BASE 0xF0300000u
#define RASPI3_KERNEL_MMIO_USB_BASE  0xF0400000u
#define RASPI3_KERNEL_MMIO_SECTION   0x00100000u

#define ARMOS_PLATFORM_NAME                      "Raspberry Pi 3"
#define ARMOS_PLATFORM_CPU_MODEL                 "ARM Cortex-A53 @ Raspberry Pi 3 (AArch32)"
#define ARMOS_PLATFORM_CPU_FEATURES              "swp half thumb fastmult vfp edsp neon vfpv4 tls"
#define ARMOS_PLATFORM_HARDWARE_NAME             "ArmOS Raspberry Pi 3"
#define ARMOS_PLATFORM_RAM_START                 RASPI3_RAM_START
#define ARMOS_PLATFORM_RAM_FALLBACK_SIZE         (RASPI3_PERIPHERAL_BASE - RASPI3_RAM_START)
#define ARMOS_PLATFORM_KERNEL_DIRECT_MAP_PHYS_END RASPI3_PERIPHERAL_BASE
#define ARMOS_PLATFORM_RAM_PROBE_MAX_MB          1008u
#define ARMOS_PLATFORM_DEFAULT_CPU_COUNT         4u
#define ARMOS_PLATFORM_TIMER_FALLBACK_HZ         1000000u
#define ARMOS_PLATFORM_TIMER_CNTFRQ_QUIRK_HZ     19200000u
#define ARMOS_PLATFORM_TIMER_CNTFRQ_QUIRK_EFFECTIVE_HZ 1000000u
#define ARMOS_PLATFORM_DEVICE_START              RASPI3_PERIPHERAL_BASE
#define ARMOS_PLATFORM_DEVICE_END                RASPI3_PERIPHERAL_END

#define ARMOS_PLATFORM_UART0_PHYS_BASE           RASPI3_UART0_BASE
#define ARMOS_PLATFORM_UART0_PHYS_SECTION_BASE   RASPI3_UART0_SECTION_BASE
#define ARMOS_PLATFORM_UART0_KERNEL_BASE \
    (RASPI3_KERNEL_MMIO_UART_BASE + (RASPI3_UART0_BASE - RASPI3_UART0_SECTION_BASE))
#define ARMOS_PLATFORM_UART0_CLOCK_HZ            4000000u
#define ARMOS_PLATFORM_UART0_BAUD                115200u
#define ARMOS_PLATFORM_GPIO_KERNEL_BASE          RASPI3_KERNEL_MMIO_UART_BASE

/* 2.8-inch ILI9341 shield, write-only 8080 bus; RD is tied high. */
#define ARMOS_PLATFORM_ILI9341_D0_PIN             4u
#define ARMOS_PLATFORM_ILI9341_D1_PIN             17u
#define ARMOS_PLATFORM_ILI9341_D2_PIN             18u
#define ARMOS_PLATFORM_ILI9341_D3_PIN             27u
#define ARMOS_PLATFORM_ILI9341_D4_PIN             22u
#define ARMOS_PLATFORM_ILI9341_D5_PIN             23u
#define ARMOS_PLATFORM_ILI9341_D6_PIN             24u
#define ARMOS_PLATFORM_ILI9341_D7_PIN             25u
#define ARMOS_PLATFORM_ILI9341_CS_PIN              5u
#define ARMOS_PLATFORM_ILI9341_DC_PIN              6u
#define ARMOS_PLATFORM_ILI9341_WR_PIN              12u
#define ARMOS_PLATFORM_ILI9341_RESET_PIN           13u

#define ARMOS_PLATFORM_UART_IRQ                  57u
#define ARMOS_PLATFORM_TIMER_IRQ                 1u
#define ARMOS_PLATFORM_SGI_TLB_SHOOTDOWN_IRQ     0u

#define ARMOS_PLATFORM_KERNEL_MMIO_SECTION_SIZE  RASPI3_KERNEL_MMIO_SECTION
#define ARMOS_PLATFORM_KERNEL_MMIO_IRQCTRL_BASE  RASPI3_KERNEL_MMIO_IRQ_BASE
#define ARMOS_PLATFORM_KERNEL_MMIO_UART_BASE     RASPI3_KERNEL_MMIO_UART_BASE
#define ARMOS_PLATFORM_KERNEL_MMIO_EMMC_BASE     RASPI3_KERNEL_MMIO_EMMC_BASE
#define ARMOS_PLATFORM_KERNEL_MMIO_SDHOST_BASE \
    (RASPI3_KERNEL_MMIO_UART_BASE + \
     (RASPI3_SDHOST_BASE - RASPI3_UART0_SECTION_BASE))
#define ARMOS_PLATFORM_KERNEL_MMIO_IRQCTRL2_BASE \
    RASPI3_KERNEL_MMIO_IRQCTRL2_BASE
#define ARMOS_PLATFORM_KERNEL_MMIO_USB_BASE \
    (RASPI3_KERNEL_MMIO_USB_BASE + (RASPI3_USB_BASE - RASPI3_USB_SECTION_BASE))
#define ARMOS_PLATFORM_KERNEL_MMIO_USB_SECTION_BASE RASPI3_KERNEL_MMIO_USB_BASE
#define ARMOS_PLATFORM_USB_PHYS_SECTION_BASE RASPI3_USB_SECTION_BASE
#define ARMOS_PLATFORM_IRQCTRL2_PHYS_SECTION_BASE \
    RASPI3_IRQCTRL_SECTION_BASE
#define ARMOS_PLATFORM_IRQCTRL2_PHYS_BASE         RASPI3_IRQCTRL_BASE

#define ARMOS_PLATFORM_HAS_EMMC                  1u
#define ARMOS_PLATFORM_EMMC_PHYS_BASE            RASPI3_EMMC_BASE
#define ARMOS_PLATFORM_EMMC_PHYS_SECTION_BASE    RASPI3_EMMC_SECTION_BASE
#define ARMOS_PLATFORM_EMMC_KERNEL_BASE \
    (RASPI3_KERNEL_MMIO_EMMC_BASE + (RASPI3_EMMC_BASE - RASPI3_EMMC_SECTION_BASE))

#define ARMOS_PLATFORM_IRQCTRL_PHYS_START        RASPI3_LOCAL_IRQ_BASE
#define ARMOS_PLATFORM_IRQCTRL_PHYS_END          RASPI3_LOCAL_IRQ_END
#define ARMOS_PLATFORM_IRQ_TARGETS_AUTO_MANAGED  0
#define ARMOS_PLATFORM_HAS_PSCI                  0
#define ARMOS_PLATFORM_HAS_SMP_IPI               1u

#endif /* _ASM_ARM32_PLATFORM_RASPI3_H */
