#ifndef ARMOS_BSDMTREE_NBTOOL_CONFIG_H
#define ARMOS_BSDMTREE_NBTOOL_CONFIG_H

#ifndef HAVE_NBTOOL_CONFIG_H
#define HAVE_NBTOOL_CONFIG_H 1
#endif

#define HAVE_STRUCT_STAT_ST_FLAGS 0
#define HAVE_NETDB_H 0

#endif /* ARMOS_BSDMTREE_NBTOOL_CONFIG_H */
