#ifndef ARMOS_BSDPAX_TZFILE_H
#define ARMOS_BSDPAX_TZFILE_H

#define SECSPERMIN 60
#define MINSPERHOUR 60
#define HOURSPERDAY 24
#define SECSPERHOUR (SECSPERMIN * MINSPERHOUR)
#define SECSPERDAY ((long)SECSPERHOUR * HOURSPERDAY)
#define DAYSPERNYEAR 365
#define TM_YEAR_BASE 1900

#endif /* ARMOS_BSDPAX_TZFILE_H */
